name: Deploy Hugo to Pages (manual)
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "branch/tag/SHA to deploy"
        required: true
        default: "main"
        type: string
      include_drafts:
        description: "Include drafts (-D)"
        required: false
        default: false
        type: boolean

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}
          submodules: true
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.128.0"
          extended: true
      - run: |
          if [ "${{ inputs.include_drafts }}" = "true" ]; then
            hugo -D --minify
          else
            hugo --minify
          fi
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment: { name: github-pages }
    steps:
      - uses: actions/deploy-pages@v4
